---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${rootArtifactId}-silo
  labels:
    team: ${team}
    app: ${rootArtifactId}-silo

spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0

  selector:
    matchLabels:
      app: ${rootArtifactId}-silo

  template:
    metadata:
      name: ${rootArtifactId}-silo
      labels:
        team: ${team}
        app: ${rootArtifactId}-silo
        rebuy.com/toolstack: jvm.spring-boot.v2.6
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        sidecar.istio.io/inject: "true"

    spec:
      terminationGracePeriodSeconds: 120
      serviceAccountName: ${rootArtifactId}-silo

      tolerations:
        - key: "rebuy.com/pool"
          operator: "Equal"
          value: "stateless"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rebuy.com/pool
                    operator: In
                    values:
                      - "stateless"

      containers:
        - name: silo
          image: "074509403805.dkr.ecr.eu-west-1.amazonaws.com/${rootArtifactId}-silo:{{.gitCommitID}}"
          imagePullPolicy: Always
          env:
            - name: SILO_PROFILE
              value: kubernetes
            - name: SILO_JAVA_ARGS
              value: >
                -XX:MaxRAMPercentage=75
                -XX:+UseG1GC
                {{ if eq .clusterName "production" }}
                -javaagent:/usr/local/newrelic/newrelic.jar
                -Dnewrelic.config.app_name=${rootArtifactId}-silo
                -Dnewrelic.config.license_key=${newrelicLicenseKey}
                {{ end }}
          ports:
            - containerPort: 8080

          resources:
            limits:
              cpu: 1000m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 768Mi

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 60

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            timeoutSeconds: 1

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 1
