---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ${projectName}
  labels:
    team: ${team}
    app: ${projectName}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-ssl@kubernetescrd

spec:
  rules:
    - host: ${projectName}.{{.clusterName}}.rebuy.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${projectName}
                port:
                  number: 80
