---
apiVersion: v1
kind: Service

metadata:
  name: ${rootArtifactId}-silo
  labels:
    app: ${rootArtifactId}-silo

spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: ${rootArtifactId}-silo
    rebuy.com/live-traffic: enabled
