---
apiVersion: v1
kind: Service

metadata:
  name: ${projectName}
  labels:
    app: ${projectName}

spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: ${projectName}
    rebuy.com/live-traffic: enabled
