
stage: sandbox

clients:
    permission-client:
        host: customer-silo.localhost

remote-token-services:
    endpoint: customer-silo.localhost

consul:
    agent: 127.0.0.1

spring:
    datasource:
        url: jdbc:postgresql://localhost/rebuy

messaging:
    host: localhost
