server:
    port: CHANGEME

spring:
    datasource:
        url: jdbc:CHANGEME://${spring.config.name}.CHANGME.service.${stage}.consul/CHANGEME
        username: CHANGEME
        password: CHANGEME
        schema: CHANGEME
        maximum-pool-size: 3

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    config:
        name: CHANGEME

clients:
    permissionClient:
        clientId: ${rootArtifactId}
        secret: CHANGEME
        port: 80
        keepAliveDurationMs: 300000

flyway:
    locations: classpath:db.migration, classpath:db.common
    schemas: flyway_migrations
    table: CHANGEME

permissions:
    cache:
        duration: 24
        timeunit: h

remoteTokenServices:
    clientId: ${rootArtifactId}
    secret: CHANGEME

consul:
    name: ${spring.config.name}
    siloPort: ${server.port}
