#set($symbol_dollar = '$')

stage: vagrant

server:
    port: 0
    max-http-header-size: 32768
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    forward-headers-strategy: native

spring:
    datasource:
        url: jdbc:postgresql://vagrant.cloud/rebuy
        platform: postgresql
        username: ${symbol_dollar}{postgres_user:${symbol_dollar}{spring.application.name}}
        password: ${symbol_dollar}{postgres_password:${symbol_dollar}{spring.application.name}}
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
    application:
        name: ${projectName}
    flyway:
        locations: classpath:db/common
        schemas: ${databaseSchema}
    jpa:
        open-in-view: false

logging:
    config: classpath:vagrant/log4j2.xml

clients:
    common:
        read-timeout: 5000
        connect-timeout: 5000

rebuy:
    security:
        client-id: ${spring.application.name}
        client-secret: ${clientSecret}
        endpoint: http://customer-silo.vagrant.cloud

messaging:
    host: vagrant.cloud
    virtualHost: null
    exchange: rebuy
    durable: true
    autoDelete: false
    user: ${symbol_dollar}{rabbitmq_user:guest}
    password: ${symbol_dollar}{rabbitmq_password:guest}
    consumerExchange: rebuy
    publisherExchange: rebuy
    schema-name: ${databaseSchema}
    queue-prefix: ${spring.application.name}

management:
    endpoints:
        web:
            exposure:
                include: info, health, prometheus, mappings

web-context-logging:
    on-exception-handler: true
