stage: vagrant

server:
    port: 0
    max-http-header-size: 32768

spring:
    datasource:
        url: jdbc:postgresql://${spring.application.name}.postgres.service.${stage}.consul/rebuy
        username: ${spring.application.name}
        password: ${databasePassword}
        hikari:
            maximum-pool-size: 3

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    application:
        name: ${rootArtifactId}

    flyway:
        locations: classpath:db/migration, classpath:db/common
        schemas: flyway_migrations
        table: ${flywayTableName}
        baseline-version: "0"
        baseline-on-migrate: true

    jpa:
        open-in-view: false

clients:
    permission-client:
        clientId: ${spring.application.name}
        secret: ${clientSecret}
        host: customer-silo.vagrant.cloud
        port: 80
        keepAliveDurationMs: 300000

permissions:
    cache:
        duration: 24
        timeunit: h

remote-token-services:
    clientId: ${spring.application.name}
    secret: ${clientSecret}
    endpoint: customer-silo.vagrant.cloud
    cacheDuration: 10
    cacheTimeUnit: m
    cacheSize: 100

consul:
    name: ${spring.application.name}-silo
    agent: 192.168.33.10
    siloPort: ${server.port}

messaging:
    host: ${spring.application.name}.rabbitmq.service.${stage}.consul
    virtualHost:
    exchange: rebuy
    durable: true
    autoDelete: false
    user:
    password:
    consumerExchange: rebuy
    publisherExchange: rebuy
    schema-name: ${rootArtifactId}
    queue-prefix: ${spring.application.name}

management:
    endpoints:
        web:
            exposure:
                include: info, health, prometheus
