
stage: vagrant

server:
    port: 0
    max-http-header-size: 32768
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    forward-headers-strategy: native

spring:
    datasource:
        url: jdbc:postgresql://vagrant.cloud/rebuy
        platform: postgresql
        username: ${spring.application.name}
        password: ${spring.application.name}
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
    application:
        name: ${rootArtifactId}
    flyway:
        locations: classpath:db/common
        schemas: ${databaseSchema}
    jpa:
        open-in-view: false

logging:
    config: classpath:${stage}/log4j2.xml

clients:
    permission-client:
        clientId: ${spring.application.name}
        secret: ${clientSecret}
        host: customer-silo.vagrant.cloud
        port: 80
        keepAliveDurationMs: 300000

permissions:
    cache:
        duration: 24
        timeunit: h

remote-token-services:
    clientId: ${spring.application.name}
    secret: ${clientSecret}
    endpoint: customer-silo.vagrant.cloud
    cacheDuration: 10
    cacheTimeUnit: m
    cacheSize: 100

messaging:
    host: vagrant.cloud
    virtualHost: null
    exchange: rebuy
    durable: true
    autoDelete: false
    user: null
    password: null
    consumerExchange: rebuy
    publisherExchange: rebuy
    schema-name: ${databaseSchema}
    queue-prefix: ${spring.application.name}

management:
    endpoints:
        web:
            exposure:
                include: info, health, prometheus, mappings

opentracing:
    jaeger:
        log-spans: false
