
stage: sandbox

clients:
    permission-client:
        host: customer-silo.localhost

remote-token-services:
    endpoint: customer-silo.localhost

spring:
    datasource:
        url: jdbc:postgresql://localhost/rebuy

messaging:
    host: localhost
