silo:
  jdk: 'jdk-11'
  mailerRecipients:
    - '${mailerRecipients}'
docker:
  upstreamProjects:
    - 'rebuy-de/base-image-java/master'
  mailerRecipients:
    - '${mailerRecipients}'
  buildScript: 'deployment/bin/build'
  dockerFilePaths:
    - 'deployment/docker/Dockerfile'
  repository: ${rootArtifactId}-silo
